import { Quicksand } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Header from './components/header'
import 'bootstrap/dist/css/bootstrap.min.css'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <Header />
        <br />
        {children}
        <Footer />
      </body>
    </html>
  )
}
